theme: jekyll-theme-minimal
title: Weizheng Lai
description: Ph.D. Candidate in Economics <br> University of Maryland
logo: /assets/img/me.jpg
show_downloads: false
navigation:
  - title: Research
    url: /
  - title: Resources
    url: resources
  - title: CV
    url: /assets/pdfs/CV.pdf
