#theme: jekyll-theme-minimal
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

title: Weizheng Lai
description: Ph.D. Candidate in Economics <br> University of Maryland
logo: /assets/img/me2.jpg
show_downloads: false
navigation:
  - title: Curriculum Vitae
    url: /assets/pdfs/CV.pdf
  - title: Research
    url: /
  - title: Resources
    url: /resources
  - title: Notes
    url: /notes
  
