theme: jekyll-theme-minimal
title: Weizheng Lai
description: Ph.D. Candidate in Economics \ University of Maryland
logo: /assets/img/me.jpg
show_downloads: false
navigation:
  - title: Research
    url: /
  - title: Resources
    url: setup
  - title: CV
    url:
